<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NithyaLenova" failures="1" tests="3" name="testRunner.TestRunner" time="28.600" errors="0" timestamp="2025-07-04T11:52:08 CDT" skipped="2">
  <testcase classname="testRunner.TestRunner" name="runScenario" time="8.788">
    <failure message="Age Feild is not accepting the Invalid data and not showing Error message expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Age Feild is not accepting the Invalid data and not showing Error message expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.FreeDashboard_Step.user_should_see_error_message_DashboardAccountDetails(FreeDashboard_Step.java:288)
at âœ½.User should see Error message DashboardAccountDetails(file:///C:/Users/nithi/EclipseWorkspace2024/Team01_Sweet-Debugger/src/test/resources/features/FreeDashboard.feature:70)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="9.252">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="10.560">
    <skipped/>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.TestRunner -->
